### PR TITLE
Update Issues Template

### PR DESCRIPTION
**Pull request by jamescurtin**
**Improves the formatting & icon usage in the `issues.md` file for better ease of use. See below for before-and-after examples:** 

(Generated via `lams -i __tests__/dummy-projects/05-manifest-name/*`)

No issues found:
<table border="0">
 <tr>
    <td><b style="font-size:30px">Before</b></td>
    <td></td>
 </tr>
 <tr>
    <td><b style="font-size:30px">After</b></td>
    <td></td>
 </tr>
</table>

Issues found:
<table border="0">
 <tr>
    <td><b style="font-size:30px">Before</b></td>
    <td></td>
 </tr>
 <tr>
    <td><b style="font-size:30px">After</b></td>
    <td></td>
 </tr>
</table>

### CODE REVIEW

**Comment by fabio-looker** [comment]
I like the checkmarks when no errors, and the more varied header font sizes & new emojies. I find myself wanting the collapsible sections for at least the exemptions though. Are you not a fan of these?

**Comment by jamescurtin** [comment]
Whoops--closed by mistake! Fair point about the collapsibility: I will add back.

**Comment by jamescurtin** [comment]
Looks like the Looker UI doesn't support the `font-size` style option:
markdown-example

But here's what it looks like with rendered as Github-flavored Markdown:
image

**Comment by fabio-looker** [comment]
Still, looks better! Once we sort out the shrinkwrap issue, I'll publish this and the other changes to NPM as well

**Pull request merged**
