### PR TITLE
Exempt enhancements

### PR DESCRIPTION
**Pull request by fabio-looker**

### CODE REVIEW

**Comment by mariana-s-fernandes** [comment]
hi @fabio-looker I believe this PR has broken my linting. All views for which I've added exemption are being caught by LAMS.

They are written as such:

```
include: "/_base/myproject/myview.view.lkml"

view: +myview {

  #LAMS
  #rule_exemptions: {F4: "2023-10-19 - This model will be probably deprecated"}

  ...
```

Should I change the formatting of the exemption?

**Comment by fabio-looker** [comment]
Hi @mariana-s-fernandes - No, thiis existing format should still supported, and there are many tests for it in the test suite...

I'll try to reproduce your issue, but if I can't, I may ask you for help pinpointing the issue.

In the meantime, are you able to continue using the prior LAMS version?

**Comment by mariana-s-fernandes** [comment]
I've reverted to 3.2.0 and it's all good. Yes, I can try help debugging. This is a refinement, not sure if that could be the cause of issue. I was getting a W1 error with that format.

**Comment by fabio-looker** [comment]
@mariana-s-fernandes ok, that helps a lot, I thought originally you meant that the exemption was not working and causing, for example, F4 to error.

As for W1, this makes sense, that rule has no tests for conditional comments. I will fix this and make sure to add some tests for that going forward!

https://github.com/looker-open-source/look-at-me-sideways/issues/193

**Comment by fabio-looker** [comment]
@mariana-s-fernandes Just to follow up, today I released v3.4.2 which formalized the whitespace handling for conditional comments going forward. If you update to the suggested whitespace, it should be tested & stable going forward.

**Comment by mariana-s-fernandes** [comment]
thank you @fabio-looker ! I will test the new version!

**Comment by mariana-s-fernandes** [comment]
Just tested it and it's working well! Thank you again!

**Pull request merged**
